services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: "wat-react-frontend-image"
    container_name: "wat-react-frontend-container"
    volumes:
      - ./config/node/frontend/src:/app/src
    ports:
      - 3000:3000
    environment:
      - CHOKEDIR-USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_NAME=myapp

  geoserver:
    build:
      context: .
      dockerfile: docker/geoserver/DockerFile
    image: "wat-geoserver-image"
    container_name: "wat-geoserver-container"
    ports:
      - 9000:8080

  postgis:
    build:
      context: .
      dockerfile: docker/postgis/Dockerfile
    image: "wat-postgis-image"
    container_name: "wat-postgis-container"
    environment:
      POSTGRES_DB: wat_project
      POSTGRES_USER: wat_user
      POSTGRES_PASSWORD: wat_password
      POSTGRES_PORT: 5432
    ports:
      - 65432:5432
